### ISSUE TITLE
Issue for GLSL Methods

### ISSUE THREAD

**Issue by Illithidek** [shader-slang/slang-vscode-extension#12]
Hi, I've noticed an issue. Slang allows the use of GLSL API methods, such as unpackUnorm4x8. When using `slangc`, it is necessary to add the flag: `slangc -allow-glsl`. The syntax for these methods seems to be located in the `glsl.meta.slang` file. However, VS Code doesn't seem to recognize them.

![slang-error](https://github.com/user-attachments/assets/0283f7f1-f3f1-4237-ad1c-25cff18c1719)

I'm still new to slang, so I might be missing something. But is there a way to add support for proper highlighting of these methods?

**Comment by bmillsNV** [comment]
@Illithidek can you try to add "import glsl;" to your shader? That should make these functions available to the intellisense and the compiler without the -allow-glsl flag.

**Comment by Illithidek** [comment]
@bmillsNV Oh, I didn't have time earlier, but I've just checked. Thanks. It works great!
