### ISSUE TITLE
Highlight Sampler2D keyword

### ISSUE THREAD

**Issue by rytc** [shader-slang/slang-vscode-extension#13]
Highlight the `Sampler2D` shader input type.

**Comment by bmillsNV** [comment]
@rytc can you provide some more details here? If you're trying to report a bug, a screenshot would be great too.

**Comment by rytc** [comment]
Sorry about that, I noticed the 'Sampler2D' keyword is not highlighted with this extension

![image](https://github.com/user-attachments/assets/59c0f0ca-cabd-46e0-b72e-01b6e56cc83a)

**Comment by csyonghe** [comment]
What version are you using? On my local setup it works fine:

![image](https://github.com/user-attachments/assets/b27b23db-387f-4313-98c7-a7f8d1da024d)

**Comment by csyonghe** [comment]
It seems like the problem is with your color theme.
You can switch to the builtin Dark+ theme and you should be able to see the highlighting from the language server.
