### ISSUE TITLE
Formatting does not work on macOS

### ISSUE THREAD

**Issue by yarikpetrenko** [shader-slang/slang-vscode-extension#3]
I am having issue with code formatting it's just doesn't work. I have a Windows PC and it's working good. But recently I bought a Mac and with all the same extensions and all packages installed formatting does not work, when all other features work as expected. I use latest version of VSCode, your extension and macOS Ventura 13.2. I'm not quite figured how to show you log but sometimes when I open "Output" tab and select "Extension Host" there is a some error with C++ unfortunately cannot provide error because I cannot get it now. C++ extension of course installed and all packages.

**Comment by csyonghe** [comment]
Thank you for reporting this issue. Unfortunately none of us from the development team has access to a Mac.
If installing C++ extension doesn't work, you can always download a prebuilt version of clang-format manually, and point to the location of your clang-format in extension settings. The setting name for this is `slang.format.clangFormatLocation`.

**Comment by yarikpetrenko** [comment]
Update about issue. It seems that one of latest C++ or slang-vscode-extension fix the issue. I was regularly checking and it wasn't working few days ago. But now it's works fine, with C++ v1.14.5 and slang-vscode-extension v1.6.4.

I also didn't try using prebuilt version of clang-format.

I close the issue as it resolved for now.

**Comment by 9291Sam** [comment]
There's been a regression, I'm running into this now. 

I primarily use a mac so I can get you whatever you want in terms of logs and errors, I just need to know where to get them from.
