### ISSUE TITLE
Formatting error on comma separated boolean expressions with relational operators

### ISSUE THREAD

**Issue by Isti01** [shader-slang/slang-vscode-extension#4]
Hi!

Thank you for the amazing vs code plugin!
I noticed a small, but annoying bug when formatting code, here is the most basic example I could come up with to reproduce it:
```
void example()
{
    float value = 1;
    bool2(value<1, 1> 1);
}

```
When an `identifier` is followed by a `<`  and a `comma` and a `>` the spaces are removed between the operators and the operands.
Maybe it is handled as a generic parameter instead of two separate expressions?

**Comment by csyonghe** [comment]
Sorry for the inconvenience. The reason behind this is as you suggested: clang-format uses a heuristic to determine if the code should parse as a generic or a comparison expression. In this case it does look more like a generic. This is an open problem in context-free parsers and unfortunately given the time and resources we are unable to address this issue in the foreseeable future.
